### ISSUE TITLE
startup crash

### ISSUE THREAD

**Issue by Sailren** [OreCruncher/ThermalRecycling#1]
this one happens at startup: http://paste.ubuntu.com/10863607/

**Comment by OreCruncher** [comment]
Interesting.  I made a change that should address in the v0.2.2 release which can be found here: https://github.com/OreCruncher/ThermalRecycling/releases/tag/v0.2.2.  Give it a try and let me know if it solves the issue for you.

**Comment by Sailren** [comment]
i had set allow recipe overwrite to true in thermal expansion config for the pulverizer, is this important?

**Comment by OreCruncher** [comment]
Not sure exactly what that option does under the hood, but on the surface it allows a mod to overwrite an _existing_ recipe.  My mod does not do that.  When I work on ThermalRecycling I have the TE config file at defaults.

Have you had a chance to try the new jar to see if that crash goes away?

**Comment by Sailren** [comment]
not yet, but i will do soon

**Comment by OreCruncher** [comment]
Haven't heard back and I have not seen other reports related to this error.  If you are still having an issue let me know.

**Comment by Sailren** [comment]
i cant remember what i tried to do there, need to figure that out
