### ISSUE TITLE
NPE when opening scrapboxes

### ISSUE THREAD

**Issue by Staegrin** [OreCruncher/ThermalRecycling#10]
Sorry to bother you again. Got a new crash with the latest version 0.3.4.2

crashlog:
http://pastebin.com/cdweGbE3

**Comment by OreCruncher** [comment]
No bother. :)  I appreciate that you have reported it.  I will take a look.

EDIT:  Looks like the problem will happen sporadically when getting a potion effect from a scrap box.  The derp is on my end - need to rearrange logic.

**Comment by OreCruncher** [comment]
Find a release with a fix here: https://github.com/OreCruncher/ThermalRecycling/releases/tag/v0.3.4.3.  Marking it pre-release.  Depending I will update CurseForge with an official version later today.  Let me know if it helps address your issue.

**Comment by Staegrin** [comment]
Works perfectly. No crashes with any of the scapboxes
