### ISSUE TITLE
[Suggestion] 100% retrieve rate

### ISSUE THREAD

**Issue by WeCodingNow** [OreCruncher/ThermalRecycling#12]
How about adding an option to get 100% of items used in crafting of the item if using Core:Decompostion? You can make it a configurable option or add a new core, which is upgraded Decopmpsition core. Also, returning ingots instead of the dust would also be sweet. Also a configurable or ingame option.

**Comment by OreCruncher** [comment]
I thought about having a upgrade core that gives a better success rate when decomposing.  Not sure about 100% - need to think on that.  The other hard part is figuring out the ingredient list - maybe involve a nether star if it is going to be lossless.

As for ingots instead of dust the process has about an equal chance at giving you a dust for an ingot vs. an ingot.  Maybe it could be tied to an upgraded gear - reduce/eliminate dusting chance if it has an upgraded core.

**Comment by OreCruncher** [comment]
I produced an ALPHA release with functionality that is being discussed.  Find it here: https://github.com/OreCruncher/ThermalRecycling/releases/tag/v0.3.5ALPHA

**Comment by WeCodingNow** [comment]
I just started checking out your alpha release. I think that it is great that you can get more items back from recycling if you upgrade your core! However, it seems to me that there are some bugs. 
You see, it is possible to upgrade every decomposition core of one tier into decomposition core of another tier, even it's own.
Also, the retrieve rate for recycling items with resonant decomposition core does not seem to be 100%. Is it intended?
![2015-05-18_17 57 54](https://cloud.githubusercontent.com/assets/9677869/7681312/b038be78-fd88-11e4-9113-bcde51a36d4f.png)
![2015-05-18_17 57 57](https://cloud.githubusercontent.com/assets/9677869/7681310/b006a802-fd88-11e4-8b92-7fe6e691d5f8.png)
![2015-05-18_17 58 48](https://cloud.githubusercontent.com/assets/9677869/7681308/b004afca-fd88-11e4-89b6-63e3e5b0be23.png)
![2015-05-18_17 58 50](https://cloud.githubusercontent.com/assets/9677869/7681309/b0054c96-fd88-11e4-9c1e-3227795ec1d2.png)
![2015-05-18_18 01 58](https://cloud.githubusercontent.com/assets/9677869/7681311/b00c5450-fd88-11e4-87c0-7ffc9ab9b53e.png)

EDIT: Just noticed that it is indeed intended, and resonant decomposition core only raises the chance to keep the items to about 70%. Well, silly me :D However, it would be sweet to be able to get 100% of items back somehow.

**Comment by OreCruncher** [comment]
Actually it is about 78.5% keep rate if it isn't a dustable item if using a Resonant core.  For example, an Iron Ingot could be turned into dust, so it is 68.4% keep/10.1% dust.  Something like a bucket can't be turned into dust, so the dust chance is folded into the keep chance to get the 78.5%.

As for the 100% return rate I was thinking of another tier of core beyond resonant.  Not sure what the recipe would be - maybe the resonant core plus a nether star and some other ingredients.  Any suggestions?

EDIT:  Related to the recipes - I see it now.  Yay.

**Comment by OreCruncher** [comment]
Check out https://github.com/OreCruncher/ThermalRecycling/releases/tag/v0.3.5.1ALPHA

**Comment by WeCodingNow** [comment]
Yay! Recycling items with 100% success rate seems to work alright. And the recipe sure is fair, in my opinion. However, I have found some bugs, but I am going to open some new issues for those, because they don't seem to be related to this new mechanic.

**Comment by OreCruncher** [comment]
v0.3.5.4 has been released and includes these changes.  Closing.
