### ISSUE TITLE
Gears and TiC

### ISSUE THREAD

**Issue by WeCodingNow** [OreCruncher/ThermalRecycling#13]
Newer version of TiC allow for creating of gears through pouring 4 ingots worth of liquid metal onto liquid cast, thus you dont have to waste an additional iron ingot in crafting it. However, your mod only allows to decompose gears into 4 ingots of metal PLUS an additional iron ingot.

**Comment by OreCruncher** [comment]
It would.  The mod uses the internal Minecraft crafting recipes to "reverse" the process of crafting.  Does TiC have it's own gear type?

**Comment by WeCodingNow** [comment]
TiC has its own gear crafting recipe. It uses only 4 ingots of metal.

**Comment by OreCruncher** [comment]
Right - but the gear it produces - is it a TiC item?

**Comment by WeCodingNow** [comment]
Nope. TiC smeltery makes Thermal Foundation gears.

**Comment by OreCruncher** [comment]
Grumble.  Thanks.  I will need to think on this one.

**Comment by OreCruncher** [comment]
Made a change.  It can be picked up here. https://github.com/OreCruncher/ThermalRecycling/releases/tag/v0.3.4.4.  Let me know if it works for you.

**Comment by WeCodingNow** [comment]
Oh yes! This is awesome! Now, deconstructing gears works like a charm!

**Comment by OreCruncher** [comment]
:)
