### ISSUE TITLE
[DUPE] Iron Chests

### ISSUE THREAD

**Issue by WeCodingNow** [OreCruncher/ThermalRecycling#14]
Iron, Golden and Diamond chests have two recipes(three, if counting upgrades). For instance, you can craft iron chest using 8 iron ingotsand a chest, or using 4 iron ingots, 4 glass and a copper chest(which, in turn, is crafted from 8 copper ingots and a chest). 
However, recycling said chests returns the contents of the first crafting recipe, which leads to a duping mechanic. Well, you get less items overall(if you crafted the chest using the second recipe), BUT you still get more, say, iron, than you used in crafting.

**Comment by OreCruncher** [comment]
Decided to block the chest recipes to avoid the dupe loop.  Fixed for v0.3.5.2ALPHA: https://github.com/OreCruncher/ThermalRecycling/releases/tag/v0.3.5.2ALPHA

**Comment by OreCruncher** [comment]
v0.3.5.4 has been released and includes these changes.  Closing.
