### ISSUE TITLE
[DUPE] Impulse Itemducts

### ISSUE THREAD

**Issue by WeCodingNow** [OreCruncher/ThermalRecycling#15]
Impulse Itemducts(both normal and opaque versions) from Thermal Dynamics are getting recycled incorrectly - recycling 6 Impulse Itemducts returns 6 opaque Impulse Itemducts and Hardened Glass, while recycling 6 opaque Impulse Itemducts returns 6 Impulse Itemducts and a lead ingot. This leads to a loop, in which you can dupe hardened glass and lead ingots.
![2015-05-19_20 26 20](https://cloud.githubusercontent.com/assets/9677869/7707615/13ef2e48-fe6a-11e4-8ebf-089a2087f1a4.png)

Using ThermalRecycling-1.7.10-0.3.5.1ALPHA

**Comment by OreCruncher** [comment]
Good find.  Only way I can think of to reasonably handle is to block the decomp recipes for these pipes.  If you were to then stick them in the recycler it would scrap them.  Of course, chances are you would want to run it through a liquid transposer to remove the energized glowstone, which then would turn them into regular itemducts which can be recycled fine.

**Comment by OreCruncher** [comment]
Fixed for v0.3.5.2ALPHA: https://github.com/OreCruncher/ThermalRecycling/releases/tag/v0.3.5.2ALPHA

**Comment by OreCruncher** [comment]
v0.3.5.4 has been released and includes these changes.  Closing.
