### ISSUE TITLE
Format Error: {0}%

### ISSUE THREAD

**Issue by WeCodingNow** [OreCruncher/ThermalRecycling#16]
![2015-05-19_20 26 07](https://cloud.githubusercontent.com/assets/9677869/7707653/41cf4d8e-fe6a-11e4-8dbf-df719dbe9457.png)
ThermalRecycling-1.7.10-0.3.5.1ALPHA

**Comment by OreCruncher** [comment]
Supposed to be the current progress expressed as a %.  Cosmetic, though annoying. :)  I will fold into the next drop.

**Comment by OreCruncher** [comment]
Fixed for v0.3.5.2ALPHA: https://github.com/OreCruncher/ThermalRecycling/releases/tag/v0.3.5.2ALPHA

**Comment by OreCruncher** [comment]
v0.3.5.4 has been released and includes these changes.  Closing.
