### ISSUE TITLE
Golden apples

### ISSUE THREAD

**Issue by Staegrin** [OreCruncher/ThermalRecycling#19]
Golden apples are made by using 8 gold ingots and an apple. Recycling that golden apple gets you 8 gold nuggets back. 

Not sure if this is intentional?

**Comment by OreCruncher** [comment]
The pulverizer recipe?  Yeah, that's a bug.  Also noticed that the both versions of the golden apple are considered food items thus the decomp recipes are not available in the Thermal Recycler.  Need to address that.

**Comment by Staegrin** [comment]
Glad to be of help.

**Comment by OreCruncher** [comment]
Thank _you_.  I appreciate the fact that you report what you find.

**Comment by OreCruncher** [comment]
https://github.com/OreCruncher/ThermalRecycling/releases/tag/v0.3.5.5

**Comment by Staegrin** [comment]
Seems to be fully fixed. Keep up the good work.
