### ISSUE TITLE
Build 0.2.3 start up crash

### ISSUE THREAD

**Issue by Trixz2018** [OreCruncher/ThermalRecycling#2]
http://pastebin.com/t1ULGcvq

**Comment by OreCruncher** [comment]
Thanks for the report.  I will take a look.

**Comment by OreCruncher** [comment]
I made a quick change that should address your problem.  Please try v0.2.4.  https://github.com/OreCruncher/ThermalRecycling/releases/tag/v0.2.4

**Comment by Trixz2018** [comment]
so far the newest build works, time to address other issues and thank you for helping me out and also thank for such an amazing mod

**Comment by OreCruncher** [comment]
Thank you :)
