### ISSUE TITLE
Suggestion: block of scrap & recycling debris

### ISSUE THREAD

**Issue by Staegrin** [OreCruncher/ThermalRecycling#20]
To make block of scrap & recycling debris useful I would suggest making them have a fuel value.

Example: I've added a fuel value of 200 for recycling debris and 2000 for a block of scrap (same logic as a coal block).

**Comment by OreCruncher** [comment]
I was having similar thoughts, though I am not entirely sure if I want to go the standard furnace fuel route with them.

**Comment by Staegrin** [comment]
I'll keep the minetweaker settings until you decide. Just wanted to be able to do something useful with them.

I also add smelting recipes for ores that have no automation options. Just breaking them automaticly still creates too many item entities.

**Comment by OreCruncher** [comment]
Can you clarify the smelting recipes comment?

**Comment by Staegrin** [comment]
Several mods have ores that don't have a way to be processes apart from breaking them with pickaxe/block breakers. I use minetweaker to make smelting recipes for them so these ores are easier to automate the processing of.

Examples:
all the gem ores (ruby, sapphire...) in blue power 
both the browncoal ores from the browncoal ore mod
Sticky ore from aroma1997's dimensional world
root blocks from twilight forest can be smelted into charcoal
harvestcraft salt ore can be smelted into salt
all the mimicry ores can now be smelted

I used to do it for apatite ore from forestry until I made the suggestion to the mod developers and they made it part of the mod. Sadly it only gives you 1 and breaking it with block breaker pickaxe gives way more.

**Comment by OreCruncher** [comment]
Thought about the fuel.  I think I will make it burnable.  No sense in making yet another fuel/power system when there are several good ones out there already.

**Comment by OreCruncher** [comment]
https://github.com/OreCruncher/ThermalRecycling/releases/tag/v0.3.5.5

**Comment by Staegrin** [comment]
Seems to work perfectly. Keep up the good work.
