### ISSUE TITLE
Support for Redstone Armory

### ISSUE THREAD

**Issue by HanatakeYurii** [OreCruncher/ThermalRecycling#23]
I would suggest you to add support for Redstone Armory.
If you don't know it's an addon for Redstone Arsenal that add a tier of tools with specific behavior when turned on made in a new material named Gelid Enderium.
it's made by TehNut & TombenPotter and is active.

**Comment by OreCruncher** [comment]
https://github.com/OreCruncher/ThermalRecycling/releases/tag/v0.3.8.3

**Comment by HanatakeYurii** [comment]
Thanks :)
