### ISSUE TITLE
Issue with Buildcraft 7 and Buildcraft Additions

### ISSUE THREAD

**Issue by dirtyfargo** [OreCruncher/ThermalRecycling#25]
Thermal Recycling Version: 0.3.8.4

With the mods below installed, Thermal Recycling is causing incorrect Assembly table recipes in Buildcraft. For example, while normally you would need 1 iron and 1 redstone for an iron chipset, with thermal recycling installed, it actually requires a full stack of iron to produce one iron chipset. Also, the scroll wheel functionality of placing items into the Assembly table breaks as well. However, it seems as though without Buildcraft Additions, Thermal Recycling doesn't have this recipe breaking affect on the assembly table. Conversely, without Thermal Recycling, the  recipe breaking affect is also gone, and Buildcraft Additions works fine along side BC.

Buildcraft 7.0.x
Buildcraft additions 2.1.4, or any of the dev builds as well
Eureka 3.0.2
Cofh Core 3.0.2-262
Thermal Foundation 1.0.0-81
Thermal Expansion 4.0.1-182

**Comment by OreCruncher** [comment]
Thanks for letting me know.  This is strange because recycling doesn't go out of it's way to manipulate the BC recipes - it just reads them and makes necessary copies.  Of course, the BC 7.x API did change so maybe there are some unintended side effects.  I will take a look.

**Comment by OreCruncher** [comment]
Found a way to make things work.  Going to pull together an ALPHA build - did some other cleanup/changes for BC 7.0.x support.

**Comment by dirtyfargo** [comment]
Awesome thanks! I'll be sure to test it out when it's released =)

**Comment by OreCruncher** [comment]
Here's a link to the ALPHA build.  Gonna be a little bit before it's out on Curse.  https://github.com/OreCruncher/ThermalRecycling/releases/tag/v0.3.9ALPHA

**Comment by dirtyfargo** [comment]
Everything seems all good and fixed, Assembly table working as it should again for me! :)

**Comment by OreCruncher** [comment]
Cool!  Let me know if you encounter anything else with BC 7.0.x

**Comment by dirtyfargo** [comment]
Well, client side Alpha 0.3.9 runs fine for me, but server side, with my modpack, I am now getting a crash:
http://pastebin.com/itqrVFQN
Is this because it is not an 'official version' and I should wait to test it out server side ? :)

**Comment by OreCruncher** [comment]
No.  The issue is that some rendering code for some new things I am working on made it's way in.  I need to do some refactor work.  Should have another drop Friday.
