### ISSUE TITLE
Thermal Recycling 0.3.9Alpha Server Side Crash

### ISSUE THREAD

**Issue by dirtyfargo** [OreCruncher/ThermalRecycling#27]
Crash on server start up.
Crash Report:
http://pastebin.com/J83gRfUy
Only happens server side, with only these mods alongside it:
Cofh Core 3.0.2-262
Thermal Foundation 1.0.0-81
Thermal Expansion 4.0.1-182
Forge: 10.13.4.1448

**Comment by OreCruncher** [comment]
Here is an update: https://github.com/OreCruncher/ThermalRecycling/releases/tag/v0.3.9.1ALPHA

**Comment by dirtyfargo** [comment]
All working in this update =) Thanks for the great mod and quick fixes!

**Comment by OreCruncher** [comment]
No problem.  Let me know if you encounter more issues or have suggestions.
