### ISSUE TITLE
Textures

### ISSUE THREAD

**Issue by grompe** [OreCruncher/ThermalRecycling#40]
I think the mod needs better block and item textures. I could draw something nice. What do you think?

**Comment by OreCruncher** [comment]
The textures definitely need help.  I do software, not art. :)  If you have ideas forward them on.

**Comment by grompe** [comment]
How's this for the Recycler?

![](http://i.imgur.com/dLdh5qS.gif)

**Comment by OreCruncher** [comment]
Active face?  Looks real nice!

**Comment by grompe** [comment]
Made some more.
![](http://i.imgur.com/cWZPWCQ.png)

**Comment by OreCruncher** [comment]
So much better than what I have.  Which is the forth from the the left?

**Comment by grompe** [comment]
It's front face for the Scrap Assessor =)

Hmm, "pile of rubble" block will be tricky to improve as it is rendered like wheat, not very convincing for rubble.

**Comment by OreCruncher** [comment]
I picked it because it was easy - it takes a 2D shape and kinda makes it 3D in the world.  As mentioned I am not an artist. :)  Ideally I was hoping for something that looked like a pile of rocks.  If you could do something like that I can change how the thing is rendered.

EDIT: Scrap Accessor - the icon logic will need to be updated to take into account a face.  Not a big deal - I do like the texture.

EDIT2: Another suggestion for the pile of rubble.  I also thought of making it look like a cluster of stalagmites.  I recall one of the biome mods having something like that.

**Comment by grompe** [comment]
Here's the textures: (temp link removed)

Machine block side, bottom and top are exactly the same as Thermal Expansion, so if possible, you could reuse TE textures instead of the copy.

I couldn't think anything better for the Composter than a block with holes.

Will have to think about the pile of rubble.

**Comment by OreCruncher** [comment]
Thank you!  I can't tell you how thrilled I am with you doing this.  I will work on integrating today.  I would like to get into the pack before I do a BETA release.

On the rubble, I did googling of stalagmites for Minecraft and it seems the prefer method for rendering is sapling (essentially an X).  Don't interpret this as me being hung up on stalagmites. :)

**Comment by grompe** [comment]
Awesome. =)

Yes, indeed, a cross texture makes more sense for the rubble. Will see what I can do and test on saplings =)

**Comment by grompe** [comment]
Attempting with this texture: ![](http://i.imgur.com/75zVklD.png)

[![](http://i.imgur.com/2aWANzll.png)](http://i.imgur.com/2aWANzl.png)

I guess that's an improvement. Feel free to use if you like.

**Comment by OreCruncher** [comment]
Yes, it looks better.

**Comment by OreCruncher** [comment]
Should have all the textures as well as code changes to support (like the Jammed face on the recycler).  Let me know what you think.

**Comment by grompe** [comment]
This looks great! Now I will enjoy playing this mod even more!

I noticed that Scrap Assessor has top texture of a crafting table. This might be confusing. Do you want it to have a specific top texture? Same goes for the Composter, which still has crate texture for top and bottom face. I can make some new top textures for those machines.

**Comment by OreCruncher** [comment]
Composter I was thinking about having a top surface that looks like dirt or something similar.  Scrap Assessor - not sure what would be a good top.  I thought about having just the normal machine top, but it doesn't feel right.  I imagine the Assessor as being something similar to a worktable.

**Comment by grompe** [comment]
It's not really a crafting table though, nothing is crafted there. How about ![this](http://i.imgur.com/EHmxpqJ.png) for Assessor top texture?

**Comment by grompe** [comment]
Composter top looking like dirt? Green and brown. Got it. ![](http://i.imgur.com/1Y5fhHZ.png)

**Comment by OreCruncher** [comment]
Those look good!

**Comment by OreCruncher** [comment]
I believe all the textures were updated, so I am going to close.  Thanks Grom!
