### ISSUE TITLE
[Enhancement] Balance crafting recipes!

### ISSUE THREAD

**Issue by OreCruncher** [OreCruncher/ThermalRecycling#46]
I need your input on the crafting recipes in the mod.  I have been thinking for some time that the Thermal Recycler and base Decomp core recipes are bit expensive and needs adjustment.  I was wondering what your thoughts on this are and whether any of the other recipes need tweaking.

**Comment by spannerman79** [comment]
Personally I don't think the recipes are expensive.

The reason being is that if you happen to make 1e64 of a single item via AE2 then you have resources to burn (basically).  If you want those resources back then you need to put at least something substantial forward to obtain those resources back for your own screw up lol

ThermalRecycling allows for a player to undo their screw up.  I know its a game and all but in life its not without cost to undo a screw up - of any kind.

And after the cost of undoing that mistake (recipe cost) a player won't do the same mistake again that's for sure lol

To be honest there are other mods out there for those that like to play it easy or want a  quick game but those that enjoy minecraft and the challenges involved will feel "cheated" if those recipes are watered down in any way to something easier.

My 2 cents.

**Comment by OreCruncher** [comment]
I did make the Thermal Recycler and Core: Decomposition (Basic) cheaper in a prior build.  I think the remaining items are fine personally.  Thanks for your input.

**Comment by OreCruncher** [comment]
Closing for now.  Recipes seem to be balanced.
