### ISSUE TITLE
Interesting Decomposition Result - Amber Bearing Stone

### ISSUE THREAD

**Issue by sciguyryan** [OreCruncher/ThermalRecycling#56]
Hey there.

I thought I would leave this one here. Attempting to decompose amber bearing stone gives an interesting result: http://i.imgur.com/X41AnYu.png

It seems to be as the result of Project E (EE3 may also be affected?) since the philosophers stone gives a smelting recipe for nether amber ore and coal, giving amber bearing stone.

Maybe the solution here is to ignore recipes where items are used but not consumed?

**Comment by OreCruncher** [comment]
That is interesting.  I am going to mark this a bug for now.  Your suggesting is a good one.

**Comment by OreCruncher** [comment]
Planned changes:
- Automatically scrub items from recipe output that aren't consumed in crafting.  These items are typically tools, like ProjectE's Philosophers stone.
- Capability to ignore a recipe based on the presence of configured output stacks.  For example, ProjectE's Philosopher stone recipes usually take another agent to complete the crafting.  If these recipes were not ignored it would lead to infinite production of agents.

**Comment by OreCruncher** [comment]
Fixed:https://github.com/OreCruncher/ThermalRecycling/releases/tag/v0.4.2.3
