### ISSUE TITLE
[OpenEye] Potential crash during initial world gen

### ISSUE THREAD

**Issue by OreCruncher** [OreCruncher/ThermalRecycling#57]
If a world is being initialized for the first time it is possible to experience a crash.  The specific case is when Tinkers is generating oreberry bushes and breaks a Pile of Rubble in the process.  At this point in time during startup the loot table for the Pile of Rubble is empty causing the weighted random routines in Minecraft to bonkers.  They don't like a total weight of 0. :\

The current unpalatable workarounds are:
- Regen the world.  Since the world is first starting it may not be a big deal.
- Disable Pile of Rubble in the config file.

**Comment by OreCruncher** [comment]
Published release.

**Comment by spannerman79** [comment]
Issue still occurs in v0.4.2.4

```
java.lang.IllegalArgumentException
    at net.minecraft.util.WeightedRandom.func_76269_a(WeightedRandom.java:82)
    at net.minecraft.util.WeightedRandom.func_76274_a(WeightedRandom.java:113)
    at net.minecraftforge.common.ChestGenHooks.getOneItem(ChestGenHooks.java:240)
    at org.blockartistry.mod.ThermalRecycling.blocks.PileOfRubble.func_149749_a(PileOfRubble.java:118)
```

**Comment by OreCruncher** [comment]
Do you have a more complete call stack?

**Comment by spannerman79** [comment]
Was using ThermalRecycling-1.7.10-0.4.2.3.jar - not the just updated release to CurseForge.

Please ignore and close - my bad.
Sorry.

**Comment by OreCruncher** [comment]
lol - try the new one and let me know. :)

**Comment by spannerman79** [comment]
:ok_hand: all good :smile:
