### ISSUE TITLE
Pile of Rubble & Twilight Forest

### ISSUE THREAD

**Issue by xirixal** [OreCruncher/ThermalRecycling#58]
Using:
twilightforest-1.7.10-2.3.7
ThermalRecycling-1.7.10-0.4.2.3

The twilight forest is filled with Piles of Rubble!

![2015-06-29_00 57 31](https://cloud.githubusercontent.com/assets/8078759/8400747/0327b8b4-1dfa-11e5-9b28-f3f46e192653.png)

**Comment by OreCruncher** [comment]
lol - cool!  IIRC ground level for twilight is much less than 64.  I will see what I can do to address.

**Comment by OreCruncher** [comment]
Fix https://github.com/OreCruncher/ThermalRecycling/releases/tag/v0.4.2.5
