### ISSUE TITLE
[OpenEye] Crash when Somnia is installed...

### ISSUE THREAD

**Issue by OreCruncher** [OreCruncher/ThermalRecycling#59]
http://openeye.openmods.info/crashes/b3ca21efed95df8c7280a646e987efcc

Just a guess but it looks like Somnia is not handling an EntityItem with a null world during initialization.  ThermalRecycling uses a template EntityItem that is instantiated during startup in order to handle entity rendering in the Vending Machine block.  As such it does not have a world.

(I should also mention that my client crash call stacks have Thermal Expansion and not Thermal Recycling, so this may be a more general issue for Somnia.)

**Comment by callumerrington** [comment]
This should be fixed as of Somnia build 39 (1.5.0.39). As for MC 1.7.10, I'll release a patch which does the same thing.

**Comment by OreCruncher** [comment]
Excellent!  Thanks!

**Comment by OreCruncher** [comment]
Fixed v0.4.2.6
