### ISSUE TITLE
Game crash with achivements with a only your mod

### ISSUE THREAD

**Issue by CorneliusCornbread** [OreCruncher/ThermalRecycling#62]
I get a crash from your mod whenever I get an achievment from your mod. I do have a resource pack but it hasn't crashed with the resource pack in any other mod.

**Comment by OreCruncher** [comment]
Can you post the crash report to pastebin and link it here?  Also, what resource pack are you using?

**Comment by CorneliusCornbread** [comment]
I just figured out it not just this mod. Sorry.

**Comment by OreCruncher** [comment]
It happens. :)  Let me know if you encounter any more strangeness.
