### ISSUE TITLE
Unable to interact with Vending Machine if using top block

### ISSUE THREAD

**Issue by OreCruncher** [OreCruncher/ThermalRecycling#63]
Current interaction is limited to the base of the vending machine.  Though the bounding box extends to the top block, the player cannot interact with the top block.

**Comment by medsal15** [comment]
You can even place a block in the top block.

**Comment by OreCruncher** [comment]
Yep.   Should be address with the same fix.  Essentially I am adding a gag block to the top part of the vending machine.  It is essentially becoming a multiblock structure when placed into the world.

**Comment by OreCruncher** [comment]
Fixed v0.4.2.7
