### ISSUE TITLE
Problem with agaricraft

### ISSUE THREAD

**Issue by CorneliusCornbread** [OreCruncher/ThermalRecycling#65]
When I use agricraft with you mod with the composter it bone meals the crop holder.

**Comment by OreCruncher** [comment]
You mean the Agricraft crops?  Are there crops on the sticks?

**Comment by CorneliusCornbread** [comment]
No it's just the sticks.

**Comment by OreCruncher** [comment]
What version of Agricraft?

**Comment by CorneliusCornbread** [comment]
1.7.10 - 1.3.1

**Comment by OreCruncher** [comment]
This may be an Agricraft issue.  I will check with InfinityRaider.

**Comment by OreCruncher** [comment]
Marking as a bug for now - still researching.  There are things I can probably do to make the logic behave better.

**Comment by OreCruncher** [comment]
InfinityRaider believes the problem to be on his end.

**Comment by hron84** [comment]
I'd like to hide a light feature request here: could you add agricraft seeds as a green compost? I'd really appreciate this.

**Comment by OreCruncher** [comment]
Moved the agricraft seeds as compost material to separate entry.  Closing this issue because the root problem is in Agricraft.
