### ISSUE TITLE
[Enhancement] Immersive Engineering Support

### ISSUE THREAD

**Issue by Sasikaa** [OreCruncher/ThermalRecycling#66]
I'm sorry that I'm writing to my request. The Immersive Engineering mod is one thing, Industrial Hemp Fiber. It can produce a lot and do not have time to use. My thought is that it could be something. Whether after incineration, four or more pieces could be one string.

Sorry my BAD english, I'm Hungarian, little speak english, and translate Google Translator... SORRY!!!

4 or MUCH Industrial Hemp Fiber -----> one or MUCH string (or something)

**Comment by hron84** [comment]
@Sasikaa IIRC currently you can craft a string from a single piece of hemp fiber (in the latest Immersive Engineering). Also, all mod developer appreciate if you mention your **version numbers** in your request, especially for the mod that you reporting bug against.

**Comment by OreCruncher** [comment]
Released v0.4.3.4
