### ISSUE TITLE
Server Crash Missing Icons Version 3.4

### ISSUE THREAD

**Issue by silvertoken** [OreCruncher/ThermalRecycling#7]
Version 3.4 will not start as a server mod with RR3 pack.  I reduced the mods down to only thermal expansion and thermal recycling and updated to 3.4 and had this crash below.

http://pastebin.com/DwQ5Z83r

**Comment by OreCruncher** [comment]
Thanks for the report.  I will take a look.

**Comment by knoxhack** [comment]
I'm having the same problem http://pastebin.com/DF22XKt2 on RR3 version 3.2.6.1 all mods enable except The Erebus.

**Comment by OreCruncher** [comment]
I made a fix - can be found here: https://github.com/OreCruncher/ThermalRecycling/releases/tag/v0.3.4.1

Will be out on Curse Forge soon.

**Comment by silvertoken** [comment]
Tested it with my rr3 server and it starts now with no crashes and I was able to connect thanks!
