### ISSUE TITLE
[Enhancement] Enable Server Vending Machines for single player

### ISSUE THREAD

**Issue by pip69** [OreCruncher/ThermalRecycling#70]
As the title, I was hoping to be able to use the vending machines in a modpack, but single player counts as an op even if some one else made and locked the VM.

Maybe a config option so that on single player, unless you are in creative, you are able to use a Server Shop as an actual server shop.  Or maybe after the lock is used on it, the only way to access it is with a lock, other wise it counts as a server shop.
I hope you're able to understand that.

**Comment by OreCruncher** [comment]
Not quite understanding.  Anyone that is op/creative mode can open up a vending machine created by world gen or in server shop mode.  In my testing in a creative world I set my gamemode to 0 it opens as if a regular player opened it.

Note that an op/creative player can shift-right click a vending machine and it will open as if the player is going to trade.

**Comment by pip69** [comment]
Ignore me, I hadn't fully tested.  I had only checked it while being in creative. 
It works exactly as I was hoping it would. 
At least you helped me solve my problem, thanks

**Comment by OreCruncher** [comment]
:)
