### ISSUE TITLE
Diamond sword recycling

### ISSUE THREAD

**Issue by Staegrin** [OreCruncher/ThermalRecycling#71]
So just updated to the latest version and doing some testing. As I was looking for recipes I found that Diamond Swords only recycle into 1 diamond instead of the expected 2. Just making sure if it's a bug or an error.
![2015-08-12_21 32 11](https://cloud.githubusercontent.com/assets/8494635/9234694/a4051070-413a-11e5-95dd-8445de338391.png)

**Comment by OreCruncher** [comment]
Yeah, its a bug.  By the looks it's been there awhile. :)

**Comment by OreCruncher** [comment]
Released v0.4.3.4
