### ISSUE TITLE
ThermalRecycling 0.4.3.3 - Unable to use extraction core

### ISSUE THREAD

**Issue by GarradStacey** [OreCruncher/ThermalRecycling#72]
I'm unable to use the extraction core on scrapboxes. Tested with all varieties of scrapboxes. Can extract soul sand (one of the new additions) without issue.

![image](https://cloud.githubusercontent.com/assets/2777008/9372484/faca1e18-46d6-11e5-884e-1b1ce6413878.png)

**Comment by OreCruncher** [comment]
Released v0.4.3.4
