### ISSUE TITLE
Crash with Dragon API

### ISSUE THREAD

**Issue by medsal15** [OreCruncher/ThermalRecycling#73]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 01.09.15 09:25
Description: Ticking block entity

java.lang.NoSuchMethodError: net.minecraft.tileentity.TileEntity.updateEntity()V
    at net.minecraft.tileentity.TileEntity.updateEntity_DAPIRelay(TileEntity.java)
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.tileentity.TileEntity.updateEntity_DAPIRelay(TileEntity.java)

-- Block entity being ticked --
Details:
    Name: vendingTileEntity // org.blockartistry.mod.ThermalRecycling.machines.entity.VendingTileEntity
    Block type: ID #1822 (tile.MachineVending // org.blockartistry.mod.ThermalRecycling.machines.MachineVending)
    Block data value: 5 / 0x5 / 0b0101
    Block location: World: (113,4,-817), Chunk: (at 1,0,15 in 7,-52; contains blocks 112,0,-832 to 127,255,-817), Region: (0,-2; contains chunks 0,-64 to 31,-33, blocks 0,0,-1024 to 511,255,-513)
    Actual block type: ID #1822 (tile.MachineVending // org.blockartistry.mod.ThermalRecycling.machines.MachineVending)
    Actual block data value: 5 / 0x5 / 0b0101
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
    Level name: tests
    All players: 0 total; []
    Chunk stats: ServerChunkCache: 1204 Drop: 0
    Level seed: -4108954180123746249
    Level generator: ID 01 - flat, ver 0. Features enabled: true
    Level generator options: 
    Level spawn location: World: (300,4,-664), Chunk: (at 12,0,8 in 18,-42; contains blocks 288,0,-672 to 303,255,-657), Region: (0,-2; contains chunks 0,-64 to 31,-33, blocks 0,0,-1024 to 511,255,-513)
    Level time: 1 game time, 1 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 60104 (now: false), thunder time: 82601 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 446201240 bytes (425 MB) / 1223426048 bytes (1166 MB) up to 1223426048 bytes (1166 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmx1200M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 7, tallocated: 67
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1490 141 mods loaded, 141 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1490-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1490} [Minecraft Forge](forge-1.7.10-10.13.4.1490-1.7.10.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.4.35} [CodeChicken Core](minecraft.jar) 
    UCHIJAAAA   MCVanillaTweaks{1.0} [Mariculture - Vanilla Tweaks](minecraft.jar) 
    UCHIJAAAA   MobiusCore{1.2.5} [MobiusCore](minecraft.jar) 
    UCHIJAAAA   NotEnoughItems{1.0.4.95} [Not Enough Items](NotEnoughItems-1.7.10-1.0.4.95-universal.jar) 
    UCHIJAAAA   OpenEye{0.6} [OpenEye](OpenEye-0.6-1.7.10.jar) 
    UCHIJAAAA   OpenModsCore{0.7.3} [OpenModsCore](minecraft.jar) 
    UCHIJAAAA   <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHIJAAAA   <DragonAPI ASM>{0} [DragonAPI ASM Data Initialization](minecraft.jar) 
    UCHIJAAAA   battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye](1.7.10-MB_Battlegear2-Bullseye-1.0.8.1.jar) 
    UCHIJAAAA   MCP_BattleHearts{1.1.1} [MC+ BattleHearts]([1.7.10][1.2] MC+ BattleHearts - v1.1.1.jar) 
    UCHIJAAAA   MCP_BerryBush{1.1.1} [MC+ BerryBush]([1.7.10][1.2] MC+ BerryBush - v1.1.1.jar) 
    UCHIJAAAA   MCP_Blowpipe{1.4.0} [MC+ Blowpipe]([1.7.10][1.2] MC+ Blowpipe - v1.4.0.jar) 
    UCHIJAAAA   MCP_Wheel{1.1.2} [MC+ Wheel]([1.7.10][1.2] MC+ Wheel - v1.1.2.jar) 
    UCHIJAAAA   MCP_Cart{1.3.0} [MC+ Cart]([1.7.10][1.2] MC+ Cart - v1.3.0.jar) 
    UCHIJAAAA   MCP_ClayTools{1.1.2} [MC+ ClayTools]([1.7.10][1.2] MC+ ClayTools - v1.1.2.jar) 
    UCHIJAAAA   MCP_Clippers{1.1.2} [MC+ Clippers]([1.7.10][1.2] MC+ Clippers - v1.1.2.jar) 
    UCHIJAAAA   MCP_Cocoa{1.3.0} [MC+ Cocoa]([1.7.10][1.2] MC+ Cocoa - v1.3.0.jar) 
    UCHIJAAAA   MCP_DayCounter{1.1.2} [MC+ DayCounter]([1.7.10][1.2] MC+ DayCounter - v1.1.2.jar) 
    UCHIJAAAA   MCP_FirePit{1.0.3} [MC+ FirePit]([1.7.10][1.2] MC+ FirePit - v1.0.3.jar) 
    UCHIJAAAA   MCP_Fossil{1.1.2} [MC+ Fossil]([1.7.10][1.2] MC+ Fossil - v1.1.2.jar) 
    UCHIJAAAA   MCP_GrainMix{1.2.0} [MC+ GrainMix]([1.7.10][1.2] MC+ GrainMix - v1.2.0.jar) 
    UCHIJAAAA   MCP_Loom{1.2.3} [MC+ Loom]([1.7.10][1.2] MC+ Loom - v1.2.3.jar) 
    UCHIJAAAA   MCP_Quartz{1.3.2} [MC+ Quartz]([1.7.10][1.2] MC+ Quartz - v1.3.2.jar) 
    UCHIJAAAA   MCP_Satchel{1.3.2} [MC+ Satchel]([1.7.10][1.2] MC+ Satchel - v1.3.2.jar) 
    UCHIJAAAA   MCP_Sickle{1.0.0} [MC+ Sickle]([1.7.10][1.2] MC+ Sickle - v1.0.0.jar) 
    UCHIJAAAA   MCP_SweetPotato{1.0.1} [MC+ SweetPotato]([1.7.10][1.2] MC+ SweetPotato - v1.0.1.jar) 
    UCHIJAAAA   MCP_TrappedLadder{1.1.2} [MC+ TrappedLadder]([1.7.10][1.2] MC+ TrappedLadder - v1.1.2.jar) 
    UCHIJAAAA   MCP_Turnip{1.1.0} [MC+ Turnip]([1.7.10][1.2] MC+ Turnip - v1.1.0.jar) 
    UCHIJAAAA   MCP_Vines{1.0.1} [MC+ Vines]([1.7.10][1.2] MC+ Vines - v1.0.1.jar) 
    UCHIJAAAA   MCP_WoodenBucket{1.2.0} [MC+ WoodenBucket]([1.7.10][1.2] MC+ WoodenBucket - v1.2.0.jar) 
    UCHIJAAAA   CoFHCore{1.7.10R3.0.3} [CoFH Core](CoFHCore-[1.7.10]3.0.3-303.jar) 
    UCHIJAAAA   BuildCraft|Core{7.0.21} [BuildCraft](buildcraft-7.0.21.jar) 
    UCHIJAAAA   BuildCraft|Energy{7.0.21} [BC Energy](buildcraft-7.0.21.jar) 
    UCHIJAAAA   ActuallyAdditions{1.7.10-0.0.8.1} [Actually Additions](ActuallyAdditions-1.7.10-0.0.8.1.jar) 
    UCHIJAAAA   aobdbb{1.0.5} [Another One Bites The Dust: Berry Bushes](AOBDBB-1.0.5.jar) 
    UCHIJAAAA   Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCHIJAAAA   Artifacts{1.1.3} [Artifacts](Artifacts-1.1.3.jar) 
    UCHIJAAAA   BuildCraft|Factory{7.0.21} [BC Factory](buildcraft-7.0.21.jar) 
    UCHIJAAAA   BuildCraft|Builders{7.0.21} [BC Builders](buildcraft-7.0.21.jar) 
    UCHIJAAAA   Railcraft{9.7.0.0} [Railcraft](Railcraft_1.7.10-9.7.0.0.jar) 
    UCHIJAAAA   Artifice{1.7.10R1.1.4} [Artifice](Artifice-1.7.10-1.1.5R-399.jar) 
    UCHIJAAAA   iChunUtil{4.2.2} [iChunUtil](iChunUtil-4.2.2.jar) 
    UCHIJAAAA   BackTools{4.0.0} [BackTools](BackTools-4.0.0.jar) 
    UCHIJAAAA   BedCraftAndBeyond{${version}} [BedCraft and Beyond](bedcraftbeyond-1.7.10-1.0.5a.jar) 
    UCHIJAAAA   betterstorage{0.13.1.126} [BetterStorage](BetterStorage-1.7.10-0.13.1.126.jar) 
    UCHIJAAAA   BiblioCraft{1.10.5} [BiblioCraft](BiblioCraft[v1.10.6][MC1.7.10].jar) 
    UCHIJAAAA   buffedtools{1.1.1710.1} [Buffed Tools](BuffedTools-1.1.1710.7.jar) 
    UCHIJAAAA   BuildCraft|Silicon{7.0.21} [BC Silicon](buildcraft-7.0.21.jar) 
    UCHIJAAAA   BuildCraft|Robotics{7.0.21} [BC Robotics](buildcraft-7.0.21.jar) 
    UCHIJAAAA   BuildCraft|Transport{7.0.21} [BC Transport](buildcraft-7.0.21.jar) 
    UCHIJAAAA   CarpentersBlocks{3.3.6} [Carpenter's Blocks](Carpenter's Blocks v3.3.6 - MC 1.7.10.jar) 
    UCHIJAAAA   CartLivery{0.11.1} [Cart Livery](CartLivery-1.7.10-0.11.1.jar) 
    UCHIJAAAA   ForgeMultipart{1.2.0.345} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJAAAA   chisel{2.5.0.43} [Chisel 2](Chisel2-2.5.0.43.jar) 
    UCHIJAAAA   numina{0.4.0.127} [Numina](Numina-0.4.0.127.jar) 
    UCHIJAAAA   powersuits{0.11.0.259} [MachineMuse's Modular Powersuits](ModularPowersuits-0.11.0.259.jar) 
    UCHIJAAAA   ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.0-102.jar) 
    UCHIJAAAA   ExtraUtilities{1.2.11} [Extra Utilities](extrautilities-1.2.11.jar) 
    UCHIJAAAA   Mantle{1.7.10-0.3.2.jenkins188} [Mantle](Mantle-1.7.10-0.3.2a.jar) 
    UCHIJAAAA   ThermalExpansion{1.7.10R4.0.2B3} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.2B3-216.jar) 
    UCHIJAAAA   Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UCHIJAAAA   TConstruct{1.7.10-1.8.7.build979} [Tinkers' Construct](TConstruct-1.7.10-1.8.7.jar) 
    UCHIJAAAA   DragonAPI{1.0} [DragonAPI](DragonAPI 1.7.10 V8b.jar) 
    UCHIJAAAA   ChromatiCraft{1.0} [ChromatiCraft](ChromatiCraft 1.7.10 V8b.jar) 
    UCHIJAAAA   CompactMachines{1.7.10-1.20} [Compact Machines](compactmachines-1.7.10-1.20.jar) 
    UCHIJAAAA   cookiecore{1.4.0} [Cookie Core](CookieCore-1.7.10-1.4.0-11.jar) 
    UCHIJAAAA   craftingtweaks{1.0.23} [Crafting Tweaks](craftingtweaks-mc1.7.10-1.0.23.jar) 
    UCHIJAAAA   DummyCore{1.13} [DummyCore](DummyCore1.13.jar) 
    UCHIJAAAA   dyetopia{1.7.10-1.1.0} [Dyetopia](dyetopia-1.7.10-1.1.0.jar) 
    UCHIJAAAA   ElecCore{1.4.92} [ElecCore](ElecCore-1.7.10-1.4.92.jar) 
    UCHIJAAAA   Enchiridion{1.3} [Enchiridion](Enchiridion 2-1.7.10-2.0.2a.jar) 
    UCHIJAAAA   Enchiridion2{2.0.2a} [Enchiridion 2](Enchiridion 2-1.7.10-2.0.2a.jar) 
    UCHIJAAAA   enderutilities{0.4.1} [Ender Utilities](enderutilities-1.7.10-0.4.1.jar) 
    UCHIJAAAA   etfuturum{1.4.2} [Et Futurum](Et Futurum-1.4.2.jar) 
    UCHIJAAAA   ExpandedRedstone{1.0} [Expanded Redstone](ExpandedRedstone 1.7.10 V8a.jar) 
    UCHIJAAAA   FastCraft{1.21} [FastCraft](fastcraft-1.21.jar) 
    UCHIJAAAA   RedstoneArsenal{1.7.10R1.1.1} [Redstone Arsenal](RedstoneArsenal-[1.7.10]1.1.1-89.jar) 
    UCHIJAAAA   foundry{1.1.0.1} [Foundry](Foundry-1.7.10-1.1.0.1.jar) 
    UCHIJAAAA   ganysend{1.11.0} [Gany's End](Ganys End-1.11.0.jar) 
    UCHIJAAAA   ganysnether{1.8.1} [Gany's Nether](Ganys Nether-1.8.1.jar) 
    UCHIJAAAA   ganyssurface{1.12.5} [Gany's Surface](Ganys Surface-1.12.5.jar) 
    UCHIJAAAA   GeoStrata{1.0} [GeoStrata](GeoStrata 1.7.10 V8b.jar) 
    UCHIJAAAA   glass_shards{1.3.2} [Glass Shards](glass_shards_mc1.7.10-1.3.2.jar) 
    UCHIJAAAA   GuardianChest{1.7.10} [Guardian Chest](guardianchest-1.0.jar) 
    UCHIJAAAA   Hats{4.0.1} [Hats](Hats-4.0.1.jar) 
    UCHIJAAAA   HatStand{4.0.0} [HatStand](HatStand-4.0.0.jar) 
    UCHIJAAAA   headcrumbs{1.6.0} [Headcrumbs](Headcrumbs-1.6.0.jar) 
    UCHIJAAAA   ice_shards{1.1.1} [Ice Shards](ice_shards_mc1.7.10-1.1.1.jar) 
    UCHIJAAAA   InventoryPets{1.3.2} [Inventory Pets](inventorypets-1.7.10-1.3.2.jar) 
    UCHIJAAAA   IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) 
    UCHIJAAAA   JABBA{1.2.1} [JABBA](Jabba-1.2.1a_1.7.10.jar) 
    UCHIJAAAA   JAPTA{0.7.3} [JAPTA](JAPTA-0.7.3.jar) 
    UCHIJAAAA   Mariculture{1.7.10-1.2.4.2a} [Mariculture](Mariculture-Deluxe-1.7.10-1.2.4.2a.jar) 
    UCHIJAAAA   MariTech{1.0} [Marine Technlogy](Mariculture-Deluxe-1.7.10-1.2.4.2a.jar) 
    UCHIJAAAA   mo{0.4.0-RC3} [Matter Overdrive](MatterOverdrive-1.7.10-0.4.0-RC3.jar) 
    UCHIJAAAA   MeteorCraft{1.0} [MeteorCraft](MeteorCraft 1.7.10 V8a.jar) 
    UCHIJAAAA   testdummy{1.0} [MmmMmmMmmMmm](MmmMmmMmmMmm-1.6.jar) 
    UCHIJAAAA   MobAmputation{4.0.1} [MobAmputation](MobAmputation-4.0.1.jar) 
    UCHIJAAAA   MobDismemberment{4.0.0} [MobDismemberment](MobDismemberment-4.0.0.jar) 
    UCHIJAAAA   MoreBows2{1.2} [More Bows 2](MoreBows2-1.2.jar) 
    UCHIJAAAA   Morph{0.9.2} [Morph](Morph-Beta-0.9.2.jar) 
    UCHIJAAAA   NEIAddons{1.12.10.33} [NEI Addons](neiaddons-1.12.10.33-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|AppEng{1.12.10.33} [NEI Addons: Applied Energistics 2](neiaddons-1.12.10.33-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Botany{1.12.10.33} [NEI Addons: Botany](neiaddons-1.12.10.33-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Forestry{1.12.10.33} [NEI Addons: Forestry](neiaddons-1.12.10.33-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|CraftingTables{1.12.10.33} [NEI Addons: Crafting Tables](neiaddons-1.12.10.33-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|ExNihilo{1.12.10.33} [NEI Addons: Ex Nihilo](neiaddons-1.12.10.33-mc1.7.10.jar) 
    UCHIJAAAA   neiintegration{1.0.12} [NEI Integration](NEIIntegration-MC1.7.10-1.0.12.jar) 
    UCHIJAAAA   neresources{0.1.0.106} [Not Enough Resources](NotEnoughResources-1.7.10-0.1.0.106.jar) 
    UCHIJAAAA   OpenMods{0.7.3} [OpenMods](OpenModsLib-1.7.10-0.7.3.jar) 
    UCHIJAAAA   OpenBlocks{1.4.3} [OpenBlocks](OpenBlocks-1.7.10-1.4.3.jar) 
    UCHIJAAAA   fodc{1.6.1} [Ore Dictionary Converter](OreDictionaryConverter-1.6.1.jar) 
    UCHIJAAAA   mod_pndc{0.1} [Peaceful Nights, Dangerous Caves](pndc-1.7.10-0.1.jar) 
    UCHIJAAAA   PortalGun{4.0.0-beta-5} [PortalGun](PortalGun-4.0.0-beta-5.jar) 
    UCHIJAAAA   quiverchevsky{b100} [QuiverBow](QuiverBow_1.7.10_b100.zip) 
    UCHIJAAAA   RandomThings{2.2.4} [Random Things](RandomThings-2.2.4.jar) 
    UCHIJAAAA   RefinedRelocation{1.0.8b} [Refined Relocation](RefinedRelocation-1.7.10-1.0.8b.jar) 
    UCHIJAAAA   simplyjetpacks{1.5.1} [Simply Jetpacks](SimplyJetpacks-MC1.7.10-1.5.1.jar) 
    UCHIJAAAA   rfdrills{1.6.2} [RFDrills](RFDrills-1.7.10-1.6.2.jar) 
    UCHIJAAAA   AS_Ruins{14.7} [Ruins Spawning System](Ruins-1.7.10.jar) 
    UCHIJAAAA   Sampler{1.33} [Sampler](sampler-1.33.jar) 
    UCHIJAAAA   sodacantorches{01.04.00} [Sodacan Torches](sodacantorches-01.04.00.jar) 
    UCHIJAAAA   StevesCarts{2.0.0.b18} [Steve's Carts 2](StevesCarts2.0.0.b18.jar) 
    UCHIJAAAA   StorageDrawers{1.7.10-1.5.10} [Storage Drawers](StorageDrawers-1.7.10-1.5.10.jar) 
    UCHIJAAAA   thecorruptedsector{1.0.1} [The Corrupted Sector](TheCorruptedSector-MC1.7.10-1.0.1.jar) 
    UCHIJAAAA   ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics](ThermalDynamics-[1.7.10]1.1.0-161.jar) 
    UCHIJAAAA   TSteelworks{1.7.10-1.1.1} [Tinkers' Steelworks](TSteelworks-1.7.10-1.1.1-17.jar) 
    UCHIJAAAA   TiCTooltips{1.2.5} [TiC Tooltips](TiCTooltips-mc1.7.10-1.2.5.jar) 
    UCHIJAAAA   TMechworks{0.2.14.100} [Tinkers' Mechworks](TMechworks-1.7.10-0.2.14.100.jar) 
    UCHIJAAAA   Torched{4.0.0} [Torched](Torched-4.0.0.jar) 
    UCHIJAAAA   TrailMix{4.0.0} [TrailMix](TrailMix-4.0.0.jar) 
    UCHIJAAAA   WailaHarvestability{1.1.2} [Waila Harvestability](WailaHarvestability-mc1.7.x-1.1.2.jar) 
    UCHIJAAAA   wawla{1.3.1} [What Are We Looking At](Wawla-1.3.1-1.7.10.jar) 
    UCHIJAAAA   McMultipart{1.2.0.345} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJAAAA   libsandstone{1.0.0} [libsandstone](LibSandstone-1.0.0.jar) 
    UCHIJAAAA   aobd{2.8.2} [Another One Bites The Dust](AOBD-2.8.2.jar) 
    UCHIJAAAA   recycling{0.4.3.5} [Thermal Recycling](ThermalRecycling-1.7.10-0.4.3.5.jar) 
    UCHIJAAAA   ForgeMicroblock{1.2.0.345} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
    Class transformer null safety: found misbehaving transformers: me.guichaguri.betterfps.transformers.MathTransformer(me.guichaguri.betterfps.transformers.MathTransformer@7e5b27a9) returned non-null result: 0,me.guichaguri.betterfps.transformers.EventTransformer(me.guichaguri.betterfps.transformers.EventTransformer@ae52ac) returned non-null result: 0
    CoFHCore: -[1.7.10]3.0.3-303
    ThermalFoundation: -[1.7.10]1.2.0-102
    Mantle Environment: Environment healthy.
    ThermalExpansion: -[1.7.10]4.0.2B3-216
    TConstruct Environment: Environment healthy.
    RedstoneArsenal: -[1.7.10]1.1.1-89
    ThermalDynamics: -[1.7.10]1.1.0-161
    Stencil buffer state: Function set: GL30, pool: forge, bits: 8
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 0 / 8; []
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by OreCruncher** [comment]
Can you post the log on pastebin and provide a link?  At the moment it may be the DragonAPI:

java.lang.NoSuchMethodError: net.minecraft.tileentity.TileEntity.updateEntity()V

**Comment by medsal15** [comment]
Here it is. Pastebin couldn't handle the 700'000 lines. Paste.ee had the same problem.
https://drive.google.com/file/d/0B35nFaoZqlWJZWQtTHd5S21MYk0/view?usp=sharing

**Comment by OreCruncher** [comment]
The log provided by the pastebin is the same error, but the block being ticked is different.  Took a look at Reika's issues and it appears it was reported.  Find a link here: https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/216.  Based on Reika's comment update DragonAPI to v8a.

**Comment by OreCruncher** [comment]
Further update - it is fixed in v8c of the API.  Closing this defect. :)
