### ISSUE TITLE
Repairing an energy cell with scrap gives a creative energy cell

### ISSUE THREAD

**Issue by kaikue** [OreCruncher/ThermalRecycling#77]
![2015-09-26_16 17 15](https://cloud.githubusercontent.com/assets/2455512/10119705/e965927c-646a-11e5-8968-beacaccf81ee.png)

This also happens with capacitors.

**Comment by OreCruncher** [comment]
That's....interesting.  Thanks.

**Comment by OreCruncher** [comment]
Released v1.0.2.3 http://minecraft.curseforge.com/mc-mods/229666-thermal-recycling/files

This is an important fix to pick up.  If updating is not possible it is recommended that the anvil repair feature be disabled in the config.
