### ISSUE TITLE
[Enhancement] Configuration for tooltips

### ISSUE THREAD

**Issue by NotGyro** [OreCruncher/ThermalRecycling#79]
I'm not really fond of the idea of having scrap values show up in the tooltips of every single item in the game, when I'm not usually going to be using recyclers. Could the tooltips perhaps have a config setting to be disabled all together, or to only show up inside of your blocks' inventories?

**Comment by OreCruncher** [comment]
Set the following in the recycling.cfg file:

B:"Enable Tooltips"=false

**Comment by NotGyro** [comment]
Oh man, I went looking for it. I just must not have seen it the first time. Sorry!

**Comment by OreCruncher** [comment]
No worries.  There are a lot of options in the config file and it isn't surprising it was over looked. :)
