### ISSUE TITLE
NPE Log spam (0.3.4.1)

### ISSUE THREAD

**Issue by iarspider** [OreCruncher/ThermalRecycling#8]
The mod spams the log with NPE error in NEI Filtering: http://pastebin.com/9hBYB6Rw

**Comment by OreCruncher** [comment]
What version of NEI?

**Comment by iarspider** [comment]
NEI version 1.0.4.106. Full mod list here: http://pastebin.com/m9kuxCX7

**Comment by OreCruncher** [comment]
Thanks. I should have a patch out in a couple hours.

**Comment by OreCruncher** [comment]
Ok.  Try this release: https://github.com/OreCruncher/ThermalRecycling/releases/tag/v0.3.4.2.  If it works for you then I will push out.  I still need to dig in and find out which item in the inventory is causing the difficulty.  Let me know if it works.

**Comment by Staegrin** [comment]
New version seems to have fixed the NPE with creative search

**Comment by iarspider** [comment]
Looks like you've fixed it.
