### ISSUE TITLE
Waila tooltip seems incorrect for the vending machine

### ISSUE THREAD

**Issue by mrammy** [OreCruncher/ThermalRecycling#80]
It appears as a machine block and an unlocalized name. The bottom of the block appears to be fine and show the proper rendering
top:
![](http://i.imgur.com/tn0dhfo.png)
bottom:
![](http://i.imgur.com/DP8Z5R3.png)

Am I correct in assuming these should be the same?

**Comment by OreCruncher** [comment]
No, actually they are different blocks.  The top block is a gag block that is invisible.  Regardless, this should be easy to address.  Thanks for reporting.

What version of Waila and Thermal Recycling are you using?

**Comment by mrammy** [comment]
Waila 1.5.10 and Thermal Recycling 1.0.2.4 from Curse. I meant same as in same tooltip not the same block sorry if there was any misinformation I contributed there.

**Comment by OreCruncher** [comment]
Interesting...using 1.5.10 as well and my BETA build.  I don't see the problem. Hmm.

EDIT:  What are the other Waila related add-ons that you have installed?

EDIT2: There is special code in the TR Waila handler to proxy out the Vending Machine if the player is looking at the top vending block.  Do you have a config item set somewhere that disables this behavior?  Another example of this is how Waila hides the Monster Egg blocks from casual detection.

**Comment by OreCruncher** [comment]
Any further information related to my questions above? :)

**Comment by mrammy** [comment]
I'm still having a hard time tracking this one down

**Comment by OreCruncher** [comment]
Do you have a list of Waila add-ons that are installed?  I noticed Harvestability - wondering if there is anything else.

**Comment by mrammy** [comment]
Are you on IRC or Skype? maybe instant message is a better place to conduct a conversation about this

**Comment by OreCruncher** [comment]
No, I don't do Skype and I do not have an IRC.  What you could do is paste a link to the client log file generated by Forge.  Should answer a lot of my questions.

**Comment by mrammy** [comment]
[fml-client-latest.log](https://gist.github.com/mrammy/3a32838387628a7dbfc0) for 1.0.3.4 and 1.0.2.4 separated by "-v1.0.3.4 break" 
[waila.cfg](https://gist.github.com/mrammy/94dca00d00414947556c)

before and after pictures of v1.0.3.4 Beta. The actual block still doesn't appear.
![](http://i.imgur.com/x3sdTwQ.png)
![](http://i.imgur.com/EKGNHwh.png)

Could it potentially be NEI related? I'm using the latest version of NEI on curseforge. Seems a little weird to only affect your mod though...

**Comment by OreCruncher** [comment]
Sorry for not seeing your response sooner.  Apparently I am not getting a notification when you update. :\

Based on the log my mod is not getting a callback from Waila to register it's needs.  This means that my mod is not hooked into Waila, thus it is unable to handle the vending top.  What my mod does is replace the vending top block with the vending bottom for purposes of Waila.

Normally you should see this line in the log file:

`[10:12:09] [Client thread/INFO] [Waila/Waila]: Receiving registration request from [ recycling ] for method org.blockartistry.mod.ThermalRecycling.waila.WailaHandler.callbackRegister`

Dumb question, but is Waila enabled in the recycling.cfg file?

`# Enables/disables display of scrap information via Waila [default: true]`
`B:"Enable Waila Display"=true`

**Comment by mrammy** [comment]
I apologize I thought that was for display of scrap only. It's working now, sorry for all the fuss for basically no reason.

**Comment by OreCruncher** [comment]
No worries.  This may be indicative of the confusion about the settings.  It may be a good idea to have a separate setting specifically for enable/disable Waila, and a separate one for the scrap.  I am going to reopen to track.

**Comment by OreCruncher** [comment]
Btw, the `Enable Tooltips` option is the one that governs the display of the "Scrap Value" lines in the Waila HUD.  Setting to false should turn it off.

**Comment by mrammy** [comment]
Fine with me :). I did want them on just with shift which there's a waila.cfg for. Don't know how that got turned off

**Comment by OreCruncher** [comment]
Posted fix to CurseForge: http://minecraft.curseforge.com/projects/thermal-recycling/files/2269594
