### ISSUE TITLE
Vending Machine doesn't display some items

### ISSUE THREAD

**Issue by Goju-Sulfam** [OreCruncher/ThermalRecycling#81]
(English is not my native language, sorry for inconveniences)

Some item are not shown from the exterior of the machine, but the quantities are shown correctly. Its seem to doesn't concern thing that can be placed in the world (blocks, wire, etc) but only some items. The problem persist across restart of the server or of the game, and it's not related to resource pack.

![2015-10-18_14 28 55](https://cloud.githubusercontent.com/assets/12252406/10564160/6a5a5760-75a9-11e5-83a9-00b026b9b6dc.png)
![2015-10-18_14 29 07](https://cloud.githubusercontent.com/assets/12252406/10564182/3301ed04-75aa-11e5-9f33-e23bf07dc6ba.png)
(Vending machine displaying nothing and it's content)

![2015-10-18_14 30 00](https://cloud.githubusercontent.com/assets/12252406/10564193/9b251d66-75aa-11e5-8fa8-9cb83d93eb96.png)
(A working Vending machine, with some TC tools)

![2015-10-18_14 34 36](https://cloud.githubusercontent.com/assets/12252406/10564200/d714d546-75aa-11e5-809d-3666487f0a38.png)
(This one is partially displaying this content)

You can find the mod list here : http://gojusulfam.no-ip.biz/goju/crash_log/list.txt (tested without fastcraft and optifine, same result)

**Comment by OreCruncher** [comment]
When you say it isn't the resource pack I assume you have tried it with just the regular vanilla textures?

Also:
- What version of Forge are you using?
- Have you tried a newer version of Thermal Recycling?  In a subsequent version I changed the rendering logic to use the Item Frame item rendering and it may help.

**Comment by Goju-Sulfam** [comment]
Yes, I have tested with the default resource pack and it's the same result, i have just don't take screenshot.

I play with Resonant Rise 1.7.10, the last release in date. It's contain TR version 0.3.9.7 and forge 10.13.4.1448 on the server i own. I will test with a newer version in single player when i have time to do.

**Comment by OreCruncher** [comment]
Thanks for the update.

Generally, though, the rendering of the items is handled by Forge/Minecraft/the mod.  The Vending Machine logic just tells where the item should be rendered.

Based on your screen shots the Pam's HarvestCraft items demonstrate the issue.  I will see if I can replicate on my end.

**Comment by OreCruncher** [comment]
I cannot replicate the issue.  Try the latest BETA and let me know.

**Comment by Goju-Sulfam** [comment]
I have just tested with 1.0.2.4 (last version from curse) and the vending machine seem to work correctly, i think the resonant rise team need to upgrade the version.

**Comment by OreCruncher** [comment]
Yes, they are a little behind. :)  Nero is aware there are newer versions.  To be fair they are trying to accomplish a lot with the RR pack and they have quite a bit of work on their plate.  Let me know if you find anything else - I appreciate the feedback.
