### ISSUE TITLE
[Enhancement] Forestry 4 Compatibility

### ISSUE THREAD

**Issue by mrammy** [OreCruncher/ThermalRecycling#82]
If you could update your Forestry plugin to work with 4.0.10. I would be very grateful. Preferably you would add a version check for stable 3.6.11 or stable 4.0.10 and add recipes based on which version the player had installed. 

http://hastebin.com/eqibiyicej.vbs

**Comment by OreCruncher** [comment]
It's on my list.  At the moment Forestry is going through some internal upheaval and I am waiting for it to settle a bit.

**Comment by OreCruncher** [comment]
Released BETA: http://minecraft.curseforge.com/projects/thermal-recycling/files/2263121
