### ISSUE TITLE
[Enhancement] Create log in logs directory

### ISSUE THREAD

**Issue by mrammy** [OreCruncher/ThermalRecycling#83]
Quick suggestion. Would it be possible to have the log file in the logs directory instead of the main folder? It would really help clean up whats starting to be a really messy main instance folder for me.

**Comment by OreCruncher** [comment]
That's on my list, too. :)

**Comment by OreCruncher** [comment]
Released BETA: http://minecraft.curseforge.com/projects/thermal-recycling/files/2263121
