### ISSUE TITLE
NPE when going to creative search

### ISSUE THREAD

**Issue by Staegrin** [OreCruncher/ThermalRecycling#9]
So after updating thermal recycling from 0.3.4 to 0.3.4.1
I went to my testworld and went to the creative search and the game crashed.
crashlog:
http://pastebin.com/xTfpK6LQ

**Comment by OreCruncher** [comment]
See this issue: https://github.com/OreCruncher/ThermalRecycling/issues/8.  Looks the same.

**Comment by Staegrin** [comment]
Thanks for the quick fix.
