### ISSUE TITLE
IC2, MPS Support?

### ISSUE THREAD

**Issue by sciguyryan** [OreCruncher/ThermalRecycling#91]
I'm not sure if these are something you've ever considered but would they be suitable for your supported mods list?

Really enjoying the mod by the way, it has saved my life quite a few times - overcrafting can be a real pain!

**Comment by OreCruncher** [comment]
I'll add them to the "todo" list.  MPS = Modular Power Suits?

**Comment by sciguyryan** [comment]
Yeah, that's the one :)

**Comment by OreCruncher** [comment]
IC2 has been added.  Modular Power Suits still needs to be done.

**Comment by sciguyryan** [comment]
Thank you kindly, that's awesome!

**Comment by OreCruncher** [comment]
Going to close this one and add a separate entry for MPS.
